services:
  testdb:
    image: dbimg
    ports:
      - "3306:3306"
    volumes:
      - testdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  testapp:
    image: appimg
    ports:
      - "7070:8080"
volumes:
  testdbdata: {}