services:
  testdb:
    image: snoman1/spring-hib-db:V2
    ports:
      - "3306:3306"
    volumes:
      - testdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  testapp:
    image: snoman1/spring-hib-app:V2
    ports:
      - "7070:8080"
volumes:
  testdbdata: {}